### ISSUE TITLE
Export types for Visor, Surface, and Tabs

### ISSUE THREAD

**Issue by todrules** [tensorflow/tfjs-vis#17]
I'm using Angular 6, and I prefer to strongly-type my application. However, I found that the 3 main types (Visor, Surface, and Tabs) are not exported. Therefore, my IDE takes longer to provide feedback since it has to calculate the type. Plus, I'm not able to glance at an item to make sure that my parameters and variable assignments are correct.

Luckily, this has an easy, one-line fix. Just add this line to the bottom of src/index.ts:

`export * from './types';`

Please let me know if you have any questions.

**Comment by tafsiri** [comment]
Quick question, which IDE are you using? I'm surprised it isn't picking up the types from the types.d.ts file (all the d.ts files are bundled in the package). I happen to be using VS Code which seems to pick these up.
